services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - '${RABBITMQ_PORT:-5672}:5672'
      - '${RABBITMQ_DASH_PORT:-15672}:15672'
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'check_running']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    command: ['redis-server', '--requirepass', '${REDIS_PASS}']
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${REDIS_PASS}', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq:
  redis:
