export enum MailIntent {
  // Onboarding / boas-vindas
  WELCOME_PROFESSIONAL = 'WELCOME_PROFESSIONAL',
  WELCOME_CUSTOMER = 'WELCOME_CUSTOMER',
  CREATE_ACCOUNT_PROFESSIONAL = 'CREATE_ACCOUNT_PROFESSIONAL',
  CREATE_ACCOUNT_CUSTOMER = 'CREATE_ACCOUNT_CUSTOMER',

  // Verificação de conta (e-mail)
  VERIFY_ACCOUNT_EMAIL_OTP = 'VERIFY_ACCOUNT_EMAIL_OTP',
  VERIFY_ACCOUNT_EMAIL_LINK = 'VERIFY_ACCOUNT_EMAIL_LINK',

  // Troca de senha LOGADO (fluxo com requestId) – via OTP
  PASSWORD_CHANGE_VERIFY_OTP = 'PASSWORD_CHANGE_VERIFY_OTP',

  // Esqueci minha senha (FORA) – via LINK (ou OTP se quiser)
  PASSWORD_RESET_LINK = 'PASSWORD_RESET_LINK',
  PASSWORD_RESET_OTP = 'PASSWORD_RESET_OTP',

  // Eventos de agendamento
  NEW_APPOINTMENT_PROFESSIONAL = 'NEW_APPOINTMENT_PROFESSIONAL',
  NEW_APPOINTMENT_CUSTOMER = 'NEW_APPOINTMENT_CUSTOMER',
  APPOINTMENT_CONFIRMATION = 'APPOINTMENT_CONFIRMATION',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
  APPOINTMENT_CANCELLATION = 'APPOINTMENT_CANCELLATION',
}
