export enum SendMailTypeEnum {
  WELCOME_PROFESSIONAL = 'WELCOME_PROFESSIONAL',
  WELCOME_CUSTOMER = 'WELCOME_CUSTOMER',
  VALIDATION_CODE = 'VALIDATION_CODE',
  PASSWORD_RESET = 'PASSWORD_RESET',
  APPOINTMENT_CONFIRMATION = 'APPOINTMENT_CONFIRMATION',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
}
