export enum SendMailTypeEnum {
  WELCOME_PROFESSIONAL = 'WELCOME_PROFESSIONAL',
  WELCOME_CUSTOMER = 'WELCOME_CUSTOMER',

  CREATE_ACCOUNT_PROFESSIONAL = 'CREATE_ACCOUNT_PROFESSIONAL',
  CREATE_ACCOUNT_CUSTOMER = 'CREATE_ACCOUNT_CUSTOMER',

  VALIDATION_CODE = 'VALIDATION_CODE',

  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',

  NEW_APPOINTMENT = 'NEW_APPOINTMENT',
  APPOINTMENT_CANCELLATION = 'APPOINTMENT_CANCELLATION',
  APPOINTMENT_RESCHEDULE = 'APPOINTMENT_RESCHEDULE',
  APPOINTMENT_CONFIRMATION = 'APPOINTMENT_CONFIRMATION',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
}
