export enum SendMailTypeEnum {
  WELCOME_PROFESSIONAL = 'WELCOME_PROFESSIONAL',
  WELCOME_CUSTOMER = 'WELCOME_CUSTOMER',

  CREATE_ACCOUNT_PROFESSIONAL = 'CREATE_ACCOUNT_PROFESSIONAL',
  CREATE_ACCOUNT_CUSTOMER = 'CREATE_ACCOUNT_CUSTOMER',

  VALIDATION_CODE = 'VALIDATION_CODE',

  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',

  NEW_APPOINTMENT_PROFESSIONAL = 'NEW_APPOINTMENT_PROFESSIONAL',
  NEW_APPOINTMENT_CUSTOMER = 'NEW_APPOINTMENT_CUSTOMER',

  APPOINTMENT_CANCELLATION_PROFESSIONAL = 'APPOINTMENT_CANCELLATION_PROFESSIONAL',
  APPOINTMENT_CANCELLATION_CUSTOMER = 'APPOINTMENT_CANCELLATION_CUSTOMER',

  APPOINTMENT_CONFIRMATION = 'APPOINTMENT_CONFIRMATION',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
}
