export enum SendWhatsAppTypeEnum {
  VALIDATION_CODE = 'VALIDATION_CODE',

  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',

  APPOINTMENT_CANCELLATION_PROFESSIONAL = 'APPOINTMENT_CANCELLATION_PROFESSIONAL',
  APPOINTMENT_CANCELLATION_CUSTOMER = 'APPOINTMENT_CANCELLATION_CUSTOMER',

  APPOINTMENT_CONFIRMATION = 'APPOINTMENT_CONFIRMATION',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
}
